### ISSUE TITLE
如果用if判断string，会区分大小写吗？

### ISSUE THREAD

**Issue by IsaZhang** [7devs/vol1_seven#2]
如果用if判断string，会区分大小写吗？
同理，如果用case区分string，会区分大小写吗？
同理，如果用if或者case进行区分，会区分数据种类吗？

我去试一试，试完了再把issue close掉~~~~

**Comment by IsaZhang** [comment]
啊啊啊我知道啦，关键是要看if 从句的条件里写的是 == 还是 ===。

我记得Seven嘱咐过，不要弄混 = 是赋值，==和===才是判断……果然，又错了，哈哈

**Comment by dofy** [comment]
good job!!!

这就是做实验的精髓所在，听别人说的与自己经验所得的区别。
这样你永远不会忘记了。
